// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-4aQeMTxdHpcKS0mzhSz0gkS_iVIbejk',
    appId: '1:328896889583:web:8290c9555b75d0d8d0511a',
    messagingSenderId: '328896889583',
    projectId: 'nutribuddy-4e3b7',
    authDomain: 'nutribuddy-4e3b7.firebaseapp.com',
    storageBucket: 'nutribuddy-4e3b7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB09BF-yrchNKdPCihCGuDBTex1ubljEKI',
    appId: '1:328896889583:android:3c3b9de0dd8192a8d0511a',
    messagingSenderId: '328896889583',
    projectId: 'nutribuddy-4e3b7',
    storageBucket: 'nutribuddy-4e3b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-4aQeMTxdHpcKS0mzhSz0gkS_iVIbejk',
    appId: '1:328896889583:ios:YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '328896889583',
    projectId: 'nutribuddy-4e3b7',
    storageBucket: 'nutribuddy-4e3b7.firebasestorage.app',
    iosClientId:
        '328896889583-8lruno0kil4a82km8luhdmpfr1qduk4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.amdChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-4aQeMTxdHpcKS0mzhSz0gkS_iVIbejk',
    appId: '1:328896889583:ios:YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '328896889583',
    projectId: 'nutribuddy-4e3b7',
    storageBucket: 'nutribuddy-4e3b7.firebasestorage.app',
    iosClientId:
        '328896889583-8lruno0kil4a82km8luhdmpfr1qduk4k.apps.googleusercontent.com',
    iosBundleId: 'com.example.amdChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-4aQeMTxdHpcKS0mzhSz0gkS_iVIbejk',
    appId: '1:328896889583:web:8290c9555b75d0d8d0511a',
    messagingSenderId: '328896889583',
    projectId: 'nutribuddy-4e3b7',
    authDomain: 'nutribuddy-4e3b7.firebaseapp.com',
    storageBucket: 'nutribuddy-4e3b7.firebasestorage.app',
  );
}
